[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
lib_deps =
    mandulaj/PZEM-004T-v30@^1.1.2
    bblanchon/ArduinoJson@^7.0.0
    adafruit/RTClib@^2.1.1
    links2004/WebSockets@^2.4.0
